export const quiz = {
  totalQuestions: 5,
  questions: [
    {
      id: 1,
      question: "Wich is the real paint name?",
      answers: [
        "English Muffin: A7850G",
        "Seldom seen: F7780C",
        "Palladin: B0550N",
        "Picnic Basket: A3390R ",
      ],
      correctAnswer: "Palladin: B0550N",
      color: "rgba(185, 166, 149, 255)",
      src: "#",
    },
    {
      id: 2,
      question: "What is the largest Planet in the solar system",
      answers: ["Mars", "Venus", "Jupiter", "Saturn"],
      correctAnswer: "Jupiter",
      color: "rgba(185, 166, 149, 255)",
      src: "#",
    },
    {
      id: 3,
      question: "What is the smallest country in the world",
      answers: ["Monaco", "Maldives", "Vatican City", "Monaco"],
      correctAnswer: "Vactican City",
      color: "rgba(185, 166, 149, 255)",
      src: "#",
    },
    {
      id: 4,
      question: "What is the most wildly spoken language in the world",
      answers: ["English", "Spanish", "Mandarin", "Hindi"],
      correctAnswer: "Mandarin",
      color: "rgba(185, 166, 149, 255)",
      src: "#",
    },
    {
      id: 5,
      question: "What is the best food",
      answers: ["Bread", "Pizza", "Potatoes", "Celery"],
      correctAnswer: "Potatoes",
      color: "rgba(185, 166, 149, 255)",
      src: "#",
    },
  ],
};